### ISSUE TITLE
GitHub integration with our Trello board

### ISSUE THREAD

**Issue by jurrrgis** [TheStalwart/osu.lv#2]
Please integrate the Trello board to GitHub somehow, because I would love to see the Issues inside of here too!
I have heard it is possible to achieve, but don't have any time to do it myself at the moment.

Alternatively we can **switch to Projects board** right here on GitHub, feel free to discuss your opinions on it here. =w=

**Comment by TheStalwart** [comment]
Two-way integration is paid feature. Not sure you want to pay for that.

> Unito is free to try for 14 days, no credit card required. After that, you'll need to subscribe to one of our paid plans.

"Regular" integration is done on Trello side, and considering i have no idea what Trello account you're talking about, feel free to investigate and come back to ask for persmissions required: https://trello.com/power-ups/55a5d916446f517774210004/github

However, if permissions required by this integration are not repo-scale, but account/organization scale - i'm obviously not integrating my personal GitHub account with yours whatever infrastructure. In that case - fork the repo into your account/org and i will deploy to my server from the repo you manage.

**Comment by jurrrgis** [comment]
Eh, will do it when I feel like it I guess...

**Comment by jurrrgis** [comment]
Now that I think about it, I don't think we need to implement this.
Just using Trello for features and Issues for bugs or something like that will work just fine.
Because, you know, this site isn't the only thing that we're making and the activity in the Trello board is already low.
